package parser;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 16 11:48:21 CDT 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BUSCAR = 17;
  public static final int ENDFUNCION = 5;
  public static final int Y = 22;
  public static final int X = 21;
  public static final int TIPO = 38;
  public static final int ENDREALIZAR = 11;
  public static final int MI = 18;
  public static final int ENTERO = 40;
  public static final int FUNCION = 2;
  public static final int RESTA = 32;
  public static final int TIPOTRIGGER = 43;
  public static final int PARAP = 35;
  public static final int CREAR = 6;
  public static final int NOT = 28;
  public static final int AND = 27;
  public static final int IGUALDAD = 29;
  public static final int OR = 26;
  public static final int BOOL = 42;
  public static final int COMMA = 10;
  public static final int SUMA = 31;
  public static final int IF = 13;
  public static final int ID = 37;
  public static final int MAYORIGUAL = 30;
  public static final int EOF = 0;
  public static final int RETURN = 3;
  public static final int BORRAR = 8;
  public static final int error = 1;
  public static final int DIRECCION = 20;
  public static final int ASIGNACION = 12;
  public static final int ENDIF = 15;
  public static final int ELSE = 16;
  public static final int POSICION = 19;
  public static final int REALIZAR = 9;
  public static final int ACELERACION = 24;
  public static final int THEN = 14;
  public static final int VELOCIDAD = 23;
  public static final int TIPOOBJETO = 39;
  public static final int PARCIE = 36;
  public static final int DIVISION = 34;
  public static final int ENDARGS = 4;
  public static final int ENDCREAR = 7;
  public static final int FLOTANTE = 41;
  public static final int ENDTRIGGER = 25;
  public static final int MULTIPLICACION = 33;
}

